### PR TITLE
non_diff `typejoin` and `Base.depwarn`

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
cc @willtebbutt

### CODE REVIEW

**Comment by willtebbutt** [comment]
LGTM - just needs a patch bump.

**Comment by willtebbutt** [comment]
And a test.

**Review by willtebbutt — APPROVED** [review]
LGTM. Will merge when tests pass.

**Comment by DhairyaLGandhi** [comment]
https://github.com/JuliaDiff/ChainRules.jl/runs/2370533443?check_suite_focus=true#step:6:30 suggests there is a missing symbol.

**Comment by DhairyaLGandhi** [comment]
Does `test_rrule` respect types as input? Should I use a different function?

**Comment by DhairyaLGandhi** [comment]
`rand_tangent` sure doesn't like being given types, since it would annotate types to go to `DataType`

https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/8b5e9067cec52cf97da5cceec9bc040460c5cccd/src/generate_tangent.jl#L70

**Comment by DhairyaLGandhi** [comment]
LMK what the correct way to write a test for types etc is

**Comment by willtebbutt** [comment]
Yeah, I think we're just missing a `rand_tangent` for it -- we should probably write a mini test-suite to check things that have been `@non_differentiable`d.

For now, could you just check that the rules aren't nothing?
Something like
```julia
@test frule((NO_FIELDS, DoesNotExist(), DoesNotExist()), typejoin, type1, type2) !== nothing
@test rrule(typejoin, type1, type2) !== nothing
```

**Review by willtebbutt — APPROVED** [review]
Failures on nightly, but otherwise seems fine, so I'll merge.

**Pull request merged**
