### PR TITLE
Rename `DNE` -> `DoesNotExist`

### PR DESCRIPTION
**Pull request by nickrobinson251**
- partner to https://github.com/JuliaDiff/ChainRulesCore.jl/pull/42
- ~is breaking~ Not now ChainrulesCore uses `@deprecate_binding`

### CODE REVIEW

**Comment by willtebbutt** [comment]
I assume that the motivation for this is just that `DNE` isn't very readable if you don't know what's going on, whereas `DoesNotExist` is self explanatory?

**Comment by oxinabox** [comment]
I am trying to decide if should release ChainRulesCore.jl v0.4.0
so that this can pass.

**Comment by nickrobinson251** [comment]
> I am trying to decide if should release ChainRulesCore.jl v0.4.0

contains some good stuff
- https://github.com/JuliaDiff/ChainRulesCore.jl/pull/58
- https://github.com/JuliaDiff/ChainRulesCore.jl/pull/55

**Comment by oxinabox** [comment]
good point, releasing

**Pull request merged**
