### PR TITLE
remove helper `@show X` line

### PR DESCRIPTION
**Pull request by mzgubic**
It looks like this slipped in in one fo my previous PRs

### CODE REVIEW

**Comment by willtebbutt** [comment]
Any idea what's going on with the unicode character changes?

**Comment by mzgubic** [comment]
No, sorry - this has been happening for a while now. It's really annoying. Is there a place to raise this issue with github?

**Comment by willtebbutt** [comment]
:( that's sad. Is this a github thing, or a git thing? Do you see these changes locally?

**Comment by mzgubic** [comment]
Pretty sure it's a github thing. The first time I saw this I checked locally and there were no changes showing. This particular change I've done in the GUI (edit file)

**Comment by devmotion** [comment]
Ah, the same happened to me not too long ago when I edited something on github.com. I thought I had done something wrong but probably it's Github's fault then.

**Comment by willtebbutt** [comment]
Ah I see. At the risk of being very annoying, would you mind making the changes locally and opening another PR to make it a bit cleaner? And bumping the patch while you're there I guess. (I don't feel overly strongly about this though)

**Comment by mzgubic** [comment]
yeah sure - no bump though since this is tests

**Comment by mzgubic** [comment]
interesting, if I do it locally then no funky changes, closing in favour of #404

**Pull request closed without merging**
