### PR TITLE
Minor code movement (NFC) and port some matrix types from Nabla

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by willtebbutt** [comment]
LGTM once we have testing for the new structured matrix types.

**Comment by ararslan** [comment]
Oh right, forgot that part. 😬 This was more plane work with insufficient sleep.

**Comment by willtebbutt** [comment]
:airplane: :zzz:

**Comment by ararslan** [comment]
Finally got some time to finish this up.

**Comment by willtebbutt** [comment]
LGTM :)

**Pull request merged**
