### PR TITLE
det, logdet, and logabsdet rrules for SparseMatrixCSC

### PR DESCRIPTION
**Pull request by ElOceanografo**
This PR implements determinant rrules for unstructured sparse matrices. The equivalent rules for `AbstractMatrices` didn't work, since they require calculating a matrix inverse, which errors by default for sparse matrices to avoid unintentionally creating huge dense matrices. Fortunately, the adjoint for the determinant functions does not depend on all the values of the inverse matrix (see [here](https://doi.org/10.18637/jss.v070.i05), section 4.1 and Equation 8). Using the "inverse subset" algorithm, you can efficiently calculate just the sparse subset of the inverse matrix which you need. I just implemented that algorithm in this [small package](https://github.com/ElOceanografo/SparseInverseSubset.jl/tree/main), which enabled me to write the rrules here.

I put these rules and their tests in with the "structured" matrix rule sets. Would be happy to move them to new "sparse" src and test files if that fits the organizational structure better. I am also pretty new to writing chain rules, so any feedback or corrections are more than welcome!

This PR will fix https://github.com/JuliaDiff/ChainRules.jl/issues/719, and should also help fix https://github.com/TuringLang/DistributionsAD.jl/issues/89.

### CODE REVIEW

**Comment by oxinabox** [comment]
CI is broken for this new feature on julia 1.6: 
see https://github.com/JuliaDiff/ChainRules.jl/actions/runs/5812786772/job/15758921347?pr=730#step:6:300

(It's also broken on nightly for other reasons that we are going to have to look into.
But it works for this feature on nightly.)

**Comment by oxinabox** [comment]
> I put these rules and their tests in with the "structured" matrix rule sets. 

Yes, please put them in this file:
https://github.com/JuliaDiff/ChainRules.jl/blob/main/src/rulesets/SparseArrays/sparsematrix.jl
and the tests in the matching file

**Comment by ElOceanografo** [comment]
The logs do not say exactly what broke in the tests for 1.6, but I suspect it is because prior to Julia 1.7 there was no method implemented for `logabsdet` of sparse matrices (see this [issue](https://github.com/JuliaLang/julia/issues/38463) and [PR](https://github.com/JuliaLang/julia/pull/40716)). 

If that's the problem, what's the best solution? A conditional statement that defines the missing [method](https://github.com/ElOceanografo/julia/blob/98651e6a4277ab3b227207ab2991ffbb92ab56d0/stdlib/SuiteSparse/src/umfpack.jl#L429) if `VERSION < v"1.7"`?

**Comment by ElOceanografo** [comment]
Went ahead and added a conditional definition of the method for `logabsdet` that was introduced in Julia v1.7. A little hacky, but tests pass on 1.6 now. @oxinabox let me know if that seems like an ok solution...

**Review by oxinabox — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
