### PR TITLE
use ProjectTo in Array addition

### PR DESCRIPTION
**Pull request by oxinabox**
the `reshape` was a primative version of ProjectTo i think?

### CODE REVIEW

**Comment by mcabbott** [comment]
I see it has `test_rrule(+, randn(3), randn(3,1), randn(3,1,1))` for this reshape, but maybe test Diagonal + Matrix or something?

**Comment by oxinabox** [comment]
I added 
```julia
        test_rrule(+, randn(3,3), Diagonal(randn(3)), randn(3,3,1))
        test_rrule(+, randn(3,3), Diagonal(randn(3)), Symmetric(randn(3,3)))
```

and interestingly both fail.
So some debugging to do there

**Comment by mcabbott** [comment]
The bug is that this doesn't work:
```julia
julia> ProjectTo(Diagonal([1,2,3]))(randn(3,3,1))
ERROR: MethodError: no method matching (::ProjectTo{Diagonal, ... }}}}}}}})(::Array{Float64, 3})

julia> Diagonal(randn(3)) + randn(3,3,1)  # but this does
3×3×1 Array{Float64, 3}:
```

**Comment by mcabbott** [comment]
The fix is part of https://github.com/JuliaDiff/ChainRulesCore.jl/pull/446, BTW. Which I think should be merged.

**Comment by oxinabox** [comment]
Closing infavor of #783 because I can't be bothered rasing

**Pull request closed without merging**
