### PR TITLE
Setup nightly notifications

### PR DESCRIPTION
**Pull request by omus**
Informs the Invenia team of nightly CI failures. @oxinabox setup the daily Travis CI cron job.

### CODE REVIEW

**Comment by omus** [comment]
Related:
- https://github.com/JuliaDiff/ChainRulesCore.jl/pull/72
- https://github.com/JuliaDiff/FiniteDifferences.jl/pull/55

**Comment by mattBrzezinski** [comment]
A nice to have in the future would be to also have a public mailing list, I'm sure there are some non-Invenians that might be interested in keeping up with packages.

**Comment by oxinabox** [comment]
> 

A nice to have in the future would be to also have a public  mailing list, I'm sure there are some non-Invenians that might be  interested in keeping up with packages.

Most people I think do not want to get hit with an email every time the nightly build breaks.
(Though hopefully that is rare.)
And if they do want that, we can just add them to the CI config.

**Comment by mattBrzezinski** [comment]
> Most people I think do not want to get hit with an email every time the nightly build breaks.
> (Though hopefully that is rare.)
> And if they do want that, we can just add them to the CI config recipients list.

That's true, it'd be nice to grow the OSS community and have more people contributing and involved.

**Comment by oxinabox** [comment]
Nightly emails are a thing that generally I would expect people only if it is part of their job.

**Pull request merged**
